import argparse
import bs4
import datetime
import pathlib
import re
import requests
import time
import typing

# Was originally trying to pull this using requests_html, 
# but easier to just manually visit the page and copy out the list
API_ROOT = r"https://docs.microsoft.com/en-us/windows/win32/api/"

API_TEMPLATE = """\
/*
API: {api}
API URL: {api_url}
File Creation Time: {creation_time}

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
{header_list}
"""

def parse_api(href: typing.AnyStr, api: typing.AnyStr, outdir: pathlib.Path):
    api_page = requests.get(href).content
    api_name_tidy = re.sub('\s+', '_', api.lower().strip())
    api_name_tidy = re.sub('[\(\)\-\,]', '_')
    api_name_tidy = re.sub('_+', '_').replace('_.', '.')
    api_name_tidy = api_name_tidy.replace('+', 'plus')
    
    api_file_name = api_name_tidy + '.h'
    api_file_name = outdir / api_file_name
    headers = re.findall(b'([a-zA-Z0-9_\-\.]+\.h)</a>', api_page)
    if not headers:
        print(f"No special headers required for {api}..")
        return

    headers_str = '\n'.join(f"#include <{str(header, encoding='utf-8')}>" for header in headers)
    api_file_contents = API_TEMPLATE.format(
        api=api,
        api_url=href,
        creation_time=datetime.date.today().isoformat(), 
        header_list=headers_str
    )
    output = pathlib.Path(api_file_name)
    output.write_text(api_file_contents)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--html', required=True)
    parser.add_argument('--outdir', required=True)
    args = parser.parse_args()
    outdir = pathlib.Path(args.outdir)
    outdir.mkdir(exist_ok=True)
    html = pathlib.Path(args.html).read_text()
    soup = bs4.BeautifulSoup(html, 'html.parser')
    api_links = soup.find_all('li')
    for api_link in api_links:
        href = api_link.a['href']
        api = api_link.text
        if href and api:
            parse_api(href=href, api=api, outdir=outdir)
        # I dunno if MS cares.. don't want to get blocked
        time.sleep(0.2)


if __name__ == "__main__":
    main()