/*
File Creation Time: 2021-06-07

This file was originally generated by winapi_complete. 
There is no guarantee that this will compile. Some re-ordering may/will be necessary.
*/

// Defines
#define _MSC_VER 1929
#define _WIN32_WINNT 0x0A00
#define WINVER _WIN32_WINNT
#define QCC_OS_GROUP_WINDOWS
#define SECURITY_WIN32
#define WIN32 1
#define DIRECTINPUT_VERSION 0x800
#define _AMD64_

#include <sdkddkver.h>

// Default Headers
#include <winsock2.h>
#include <windows.h>
#include <initguid.h>
#include <shlobj.h>
#include <wbemcli.h>
#include <stdbool.h>
// NTSecAPI tries to redefine some winternl things we already have
#include <NTSecAPI.h>
#include <sspi.h>

// API Headers
#include "api_headers/active_directory_domain_services.h"
#include "api_headers/active_directory_rights_management_services_sdk.h"
#include "api_headers/active_directory_service_interfaces.h"
#include "api_headers/alljoyn_api.h"
#include "api_headers/antimalware_scan_interface.h"
#include "api_headers/application_installation_and_servicing.h"
#include "api_headers/audio_devices_ddi_reference.h"
#include "api_headers/automation.h"
#include "api_headers/background_intelligent_transfer_service.h"
#include "api_headers/backup.h"
#include "api_headers/battery_devices_reference.h"
#include "api_headers/bluetooth.h"
#include "api_headers/bluetooth_devices_reference.h"
#include "api_headers/cimfs.h"
#include "api_headers/cimwin32_wmi_providers.h"
#include "api_headers/cloud_filter_api.h"
#include "api_headers/complus_component_services.h"
#include "api_headers/component_object_model_com.h"
#include "api_headers/compression_api.h"
#include "api_headers/core_audio_apis.h"
#include "api_headers/data_access_and_storage.h"
#include "api_headers/data_deduplication_api.h"
#include "api_headers/data_exchange.h"
#include "api_headers/debugging_and_authoring_support.h"
#include "api_headers/desktop_window_manager_dwm.h"
#include "api_headers/developer_licensing.h"
#include "api_headers/developer_notes.h"
#include "api_headers/device_access_api.h"
#include "api_headers/device_and_driver_installation_reference.h"
#include "api_headers/dialog_boxes.h"
#include "api_headers/direct2d.h"
#include "api_headers/direct3d_10_graphics.h"
#include "api_headers/direct3d_11_graphics.h"
#include "api_headers/direct3d_12_graphics.h"
#include "api_headers/direct3d_9_graphics.h"
#include "api_headers/directcomposition.h"
#include "api_headers/directdraw.h"
//#include "api_headers/directml.h"
//#include "api_headers/directwrite.h"
//#include "api_headers/directxmath.h"
#include "api_headers/direct_manipulation.h"
#include "api_headers/display_devices_reference.h"
#include "api_headers/distributed_file_system.h"
#include "api_headers/distributed_transaction_coordinator_wmi_provider.h"
#include "api_headers/domain_name_system_dns.h"
//#include "api_headers/dxcore.h"
#include "api_headers/dxgi.h"
#include "api_headers/dynamic_host_configuration_protocol_dhcp.h"
#include "api_headers/enhanced_storage.h"
#include "api_headers/event_tracing.h"
#include "api_headers/extensible_authentication_protocol.h"
#include "api_headers/extensible_authentication_protocol_host.h"
#include "api_headers/fax_service.h"
#include "api_headers/file_server_resource_manager.h"
#include "api_headers/game_mode.h"
#include "api_headers/gaming_device_information.h"
//#include "api_headers/gdiplus.h"
#include "api_headers/group_policy_api.h"
#include "api_headers/group_policy_management_console.h"
#include "api_headers/high_dpi.h"
#include "api_headers/hlsl.h"
#include "api_headers/http_server_api.h"
#include "api_headers/human_interface_devices_reference.h"
#include "api_headers/hyper_v_management.h"
#include "api_headers/hyper_v_wmi_provider.h"
#include "api_headers/image_mastering_api.h"
#include "api_headers/indexing_service.h"
#include "api_headers/ink_input.h"
#include "api_headers/installable_file_systems_ddi_reference.h"
#include "api_headers/interaction_context.h"
#include "api_headers/internationalization_for_windows_applications.h"
#include "api_headers/ip_helper.h"
#include "api_headers/iscsi_discovery_library_api.h"
//#include "api_headers/kernel_mode_driver_reference.h"
#include "api_headers/legacy_windows_environment_features.h"
#include "api_headers/lightweight_directory_access_protocol.h"
#include "api_headers/location_api.h"
#include "api_headers/magnification_api.h"
#include "api_headers/management_information_base.h"
#include "api_headers/menus_and_other_resources.h"
#include "api_headers/microsoft_html_help_1.4.h"
#include "api_headers/microsoft_media_foundation.h"
#include "api_headers/mobile_broadband.h"
#include "api_headers/mobile_device_management_registration.h"
#include "api_headers/monitor_configuration.h"
#include "api_headers/ms_chap_password_management_api.h"
#include "api_headers/multicast_address_dynamic_client_allocation_protocol_madcap.h"
#include "api_headers/native_wifi.h"
#include "api_headers/netbios.h"
#include "api_headers/netshell.h"
#include "api_headers/network_access_protection.h"
#include "api_headers/network_diagnostics_framework.h"
#include "api_headers/network_drivers,_windows_vista_and_later.h"
#include "api_headers/network_list_manager.h"
#include "api_headers/network_management.h"
#include "api_headers/network_policy_server.h"
#include "api_headers/offline_files.h"
#include "api_headers/oobe_apis_for_setup_state_and_notification.h"
#include "api_headers/other_devices_technologies.h"
#include "api_headers/packaging_deployment_and_query_of_windows_store_apps.h"
#include "api_headers/packaging.h"
#include "api_headers/parental_controls.h"
#include "api_headers/peer_to_peer.h"
#include "api_headers/performance_counters.h"
#include "api_headers/performance_logs_and_alerts.h"
#include "api_headers/picture_acquisition.h"
#include "api_headers/power_metering_and_budgeting_reference.h"
#include "api_headers/process_snapshotting.h"
#include "api_headers/process_status_api_psapi.h"
#include "api_headers/projected_file_system.h"
#include "api_headers/quality_of_service_qos.h"
#include "api_headers/remote_assistance.h"
#include "api_headers/remote_desktop_services.h"
#include "api_headers/remote_differential_compression.h"
#include "api_headers/remote_procedure_call_rpc.h"
#include "api_headers/restart_manager.h"
#include "api_headers/routing_and_remote_access_service.h"
#include "api_headers/security_and_identity.h"
#include "api_headers/serial_controller_driver_reference.h"
#include "api_headers/settings_management_infrastructure_smi.h"
#include "api_headers/simple_network_management_protocol.h"
#include "api_headers/software_device_api.h"
#include "api_headers/structured_storage.h"
#include "api_headers/system_event_notification_service.h"
#include "api_headers/system_monitor.h"
#include "api_headers/system_restore.h"
#include "api_headers/system_services.h"
#include "api_headers/tablet_pc.h"
#include "api_headers/tapi_2.2.h"
#include "api_headers/task_scheduler.h"
#include "api_headers/telephony_application_programming_interfaces.h"
#include "api_headers/text_services_framework.h"
#include "api_headers/the_windows_shell.h"
#include "api_headers/tiles_badges_and_notifications_for_classic_desktop_applications.h"
#include "api_headers/title_callable_ui.h"
#include "api_headers/tool_help_library.h"
#include "api_headers/touch_input.h"
#include "api_headers/tpm_base_services.h"
#include "api_headers/tracelogging.h"
#include "api_headers/upnp_apis.h"
//#include "api_headers/usb_driver_reference.h"
#include "api_headers/user_access_logging.h"
#include "api_headers/virtual_hard_disk.h"
#include "api_headers/webdav.h"
#include "api_headers/websocket_protocol_component_api.h"
#include "api_headers/wia.h"
#include "api_headers/windows_accessibility_features.h"
#include "api_headers/windows_address_book.h"
#include "api_headers/windows_animation_manager.h"
//#include "api_headers/windows_biometric_framework.h"
#include "api_headers/windows_clustering.h"
#include "api_headers/windows_color_system.h"
#include "api_headers/windows_connection_manager.h"
#include "api_headers/windows_connect_now.h"
#include "api_headers/windows_contacts.h"
#include "api_headers/windows_controls.h"
#include "api_headers/windows_deployment_services.h"
#include "api_headers/windows_desktop_sharing.h"
#include "api_headers/windows_error_reporting.h"
#include "api_headers/windows_event_collector.h"
#include "api_headers/windows_event_log.h"
#include "api_headers/windows_filtering_platform.h"
#include "api_headers/windows_firewall_technologies.h"
#include "api_headers/windows_gdi.h"
#include "api_headers/windows_http_services_winhttp.h"
#include "api_headers/windows_imaging_component.h"
#include "api_headers/windows_information_protection_wip.h"
//#include "api_headers/windows_internet.h"
#include "api_headers/windows_machine_learning.h"
#include "api_headers/windows_management_infrastructure_mi.h"
#include "api_headers/windows_management_instrumentation.h"
#include "api_headers/windows_media_device_manager_11_sdk.h"
#include "api_headers/windows_messaging_mapi.h"
#include "api_headers/windows_messenger.h"
#include "api_headers/windows_mixed_reality.h"
#include "api_headers/windows_multimedia.h"
#include "api_headers/windows_network_virtualization.h"
#include "api_headers/windows_property_system.h"
#include "api_headers/windows_remote_management.h"
#include "api_headers/windows_ribbon_framework.h"
//#include "api_headers/windows_runtime_cplusplus_reference.h"
#include "api_headers/windows_search.h"
#include "api_headers/windows_server_backup.h"
#include "api_headers/windows_sockets_2.h"
#include "api_headers/windows_subsystem_for_linux.h"
#include "api_headers/windows_sync.h"
#include "api_headers/windows_system_assessment_tool.h"
#include "api_headers/windows_update_agent_api.h"
#include "api_headers/windows_web_services.h"
#include "api_headers/wpd_application_programming_interface.h"
// #include "api_headers/wpf_bitmap_effects.h"
#include "api_headers/xaml_diagnostics.h"
#include "api_headers/xaudio2_apis.h"
#include "api_headers/xblidpauthmanager.h"
#include "api_headers/xinput_game_controller_apis.h"
#include "api_headers/xml_http_extended_request.h"
#include "api_headers/xps_documents.h"

// Internals stuff via Process Hacker
#define PHNT_MODE 1             // User
#define PHNT_VERSION 109        // Version 2004 / 20H1 / 19041
// These were added to avoid some redefinitions
#define PHNT_STRINGS_DEFINED
#define PHNT_IP_GENERICS_DEFINED

// #include <phnt.h>
#include <phnt_ntdef.h>
#include <ntnls.h>
#include <ntkeapi.h>
#include <ntldr.h>
#include <ntexapi.h>
#include <ntmmapi.h>
#include <ntobapi.h>
#include <ntpsapi.h>
#include <cfg.h>
#include <ntdbg.h>
#include <ntioapi.h>
#include <ntlpcapi.h>
#include <ntpfapi.h>
#include <ntpnpapi.h>
#include <ntpoapi.h>
#include <ntregapi.h>
#include <ntrtl.h>
#include <ntseapi.h>
#include <nttmapi.h>
#include <nttp.h>
#include <ntxcapi.h>
#include <ntwow64.h>
#include <ntsam.h>
#include <ntmisc.h>
#include <ntzwapi.h>
// Too much/complete? overlap in public headers
// #include <ntd3dkmt.h>
// #include <ntlsa.h>
