/*
API: Active Directory Domain Services
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_ad/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <iads.h>
#include <adsprop.h>
#include <cmnquery.h>
#include <dsadmin.h>
#include <dsclient.h>
#include <dsgetdc.h>
#include <dsparse.h>
#include <dsquery.h>
#include <dsrole.h>
#include <ntdsapi.h>
#include <objsel.h>
#include <schedule.h>
