/*
API: Background Intelligent Transfer Service

API URL: https://docs.microsoft.com/en-us/windows/win32/api/_bits/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <bits.h>
#include <bits10_1.h>
#include <bits10_2.h>
#include <bits10_3.h>
#include <bits1_5.h>
#include <bits2_0.h>
#include <bits2_5.h>
#include <bits3_0.h>
#include <bits4_0.h>
#include <bits5_0.h>
#include <bitscfg.h>
#include <qmgr.h>
