/*
API: Component Object Model (COM)
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_com/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <accctrl.h>
#include <callobj.h>
#include <combaseapi.h>
#include <comcat.h>
#include <ctxtcall.h>
#include <dmerror.h>
#include <docobj.h>
#include <eventsys.h>
#include <guiddef.h>
#include <iaccess.h>
#include <imessagedispatcher.h>
#include <messagedispatcherapi.h>
#include <objbase.h>
#include <objidl.h>
#include <objidlbase.h>
#include <ocidl.h>
// #include <ole.h>
#include <ole2.h>
#include <oledlg.h>
#include <oleidl.h>
#include <roapi.h>
#include <rpcdce.h>
#include <shobjidl.h>
#include <txlogpub.h>
#include <unknwn.h>
#include <unknwnbase.h>
#include <urlmon.h>
#include <vbinterf.h>
// #include <winddi.h>
#include <winerror.h>
#include <wtypesbase.h>
