/*
API: Core Audio APIs
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_coreaudio/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <audioclient.h>
#include <audioendpoints.h>
#include <audioenginebaseapo.h>
#include <audioengineendpoint.h>
#include <audiopolicy.h>
#include <audiosessiontypes.h>
#include <devicetopology.h>
#include <endpointvolume.h>
#include <mmdeviceapi.h>
#include <spatialaudioclient.h>
#include <spatialaudiohrtf.h>
#include <spatialaudiometadata.h>
