/*
API: Data Access and Storage
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_fs/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <clfs.h>
#include <clfsmgmt.h>
#include <clfsmgmtw32.h>
#include <clfsw32.h>
#include <dskquota.h>
#include <fileapi.h>
#include <fileapifromapp.h>
#include <ktmtypes.h>
#include <ktmw32.h>
#include <lmshare.h>
#include <lmstats.h>
#include <lzexpand.h>
#include <ntmsapi.h>
#include <ntmsmli.h>
#include <txfw32.h>
#include <winefs.h>
#include <wofapi.h>
#include <wow64apiset.h>
