/*
API: Developer Notes
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_winprog/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <advpub.h>
#include <apiquery2.h>
#include <appcompatapi.h>
#include <aux_ulib.h>
#include <avrfsdk.h>
#include <camerauicontrol.h>
#include <capi.h>
// #include <comppkgsup.h>
#include <dciman.h>
// #include <ddrawgdi.h>
#include <editionupgradehelper.h>
#include <exdisp.h>
#include <exposeenums2managed.h>
#include <fci.h>
#include <fdi.h>
#include <fdi_fci_types.h>
#include <featurestagingapi.h>
#include <fhcfg.h>
#include <fhsvcctl.h>
#include <filehc.h>
#include <icwcfg.h>
#include <ime.h>
#include <isolatedapplauncher.h>
#include <iwscapi.h>
#include <lmaccess.h>
#include <loadperf.h>
#include <msxml.h>
#include <ntsecpkg.h>
#include <rpcndr.h>
// Overlaps with winnt
// #include <rtlsupportapi.h>
#include <stralign.h>
#include <tdiinfo.h>
#include <tcpioctl.h>
#include <vdmdbg.h>
//#include <wininet.h>
#include <winnls32.h>
#include <winreg.h>
#include <wscapi.h>
