/*
API: Direct2D
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_direct2d/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <d2d1.h>
#include <d2d1_1.h>
#include <d2d1_1helper.h>
#include <d2d1_2.h>
#include <d2d1_3.h>
#include <d2d1_3helper.h>
#include <d2d1effectauthor.h>
#include <d2d1effectauthor_1.h>
// #include <d2d1effecthelpers.h>
#include <d2d1effects.h>
#include <d2d1effects_1.h>
#include <d2d1effects_2.h>
#include <d2d1helper.h>
#include <d2d1svg.h>
#include <dcommon.h>
