/*
API: Direct3D 10 Graphics
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_direct3d10/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <d3d10.h>
#include <d3d10_1.h>
#include <d3d10_1shader.h>
#include <d3d10effect.h>
#include <d3d10misc.h>
#include <d3d10sdklayers.h>
#include <d3d10shader.h>
