/*
API: Direct3D 12 Graphics
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_direct3d12/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <d3d11on12.h>
#include <d3d12.h>
#include <d3d12sdklayers.h>
#include <d3d12shader.h>
#include <windows.graphics.holographic.interop.h>
