/*
API: Display Devices Reference
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_display/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <cloneviewhelper.h>
#include <dmemmgr.h>
#include <dxmini.h>

// Too many conflicts
//#include <ddkernel.h>
//#include <ddkmapi.h>
//#include <ddrawi.h>
//#include <ddrawint.h>
//#include <dvp.h>
