/*
API: Fax Service
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_fax/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#define WIN32 1
#include <winfax.h>
#undef WIN32
#ifdef __cplusplus
#include <faxcomex.h>
#else
#include <faxcom.h>
#endif
#include <faxdev.h>
#include <faxext.h>
#include <faxroute.h>
#include <fxsutility.h>

