/*
API: File Server Resource Manager
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_fsrm/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <fsrm.h>
#include <fsrmenums.h>
#include <fsrmpipeline.h>
#include <fsrmquota.h>
#include <fsrmreports.h>
#include <fsrmscreen.h>
#include <fsrmtlb.h>
