/*
API: Image Mastering API
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_imapi/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <imapi.h>
#include <imapi2.h>
#include <imapi2fs.h>
