/*
API: Internationalization for Windows
            Applications
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_intl/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <datetimeapi.h>
#include <elscore.h>
#include <gb18030.h>
#include <imepad.h>
#include <imm.h>
// Conflicts with dimm.h
//#include <immdev.h>
#include <msime.h>
#include <msimeapi.h>
#include <muiload.h>
#include <spellcheck.h>
#include <spellcheckprovider.h>
#include <stringapiset.h>
#include <usp10.h>
#include <winnls.h>
