/*
API: IP Helper
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_iphlp/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <ws2def.h>
#include <ws2ipdef.h>
#include <ipexport.h>
#include <iscsierr.h>
#include <icmpapi.h>
#include <ifdef.h>
#include <inaddr.h>
#include <ip2string.h>
#include <iphlpapi.h>
#include <iprtrmib.h>
#include <iptypes.h>
#include <netioapi.h>
#include <nldef.h>
#include <tcpestats.h>

