/*
API: Legacy Windows Environment Features

API URL: https://docs.microsoft.com/en-us/windows/win32/api/_lwef/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <emptyvc.h>
#include <mmcobj.h>
#ifdef __cplusplus
// Problems
// #include <ThrdBase.h>
// #include <provider.h>
 #include <reconcil.h>
#endif
#include <searchapi.h>
#include <shldisp.h>
#include <shlobj_core.h>
#include <windowsdefender.h>
#include <wmiutils.h>
