/*
API: Menus and Other Resources
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_menurc/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <resourceindexer.h>
#include <strsafe.h>
// verrsrc isn't guarded...
#ifndef VER_H
#define VER_H
#include <verrsrc.h>
#endif
#include <winver.h>
