/*
API: Microsoft Media Foundation
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_mf/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <codecapi.h>
// Conflicts with strmif.h
// #include <icodecapi.h>
#include <opmapi.h>
#include <dxva2api.h>
#include <dxva9typ.h>
#include <dxvahd.h>
#include <evr.h>
#include <evr9.h>
// Kernel Mode
// #include <ksopmapi.h>
#include <mfapi.h>
#include <mfcaptureengine.h>
#include <mfcontentdecryptionmodule.h>
#include <mfidl.h>
#include <mfmediacapture.h>
#include <mfmediaengine.h>
#include <mfmp2dlna.h>
#include <mfobjects.h>
#include <mfplay.h>
#include <mfreadwrite.h>
#include <mfsharingengine.h>
#include <mfspatialaudio.h>
#include <mftransform.h>
#include <wmcodecdsp.h>
#include <wmcontainer.h>
