/*
API: Other Devices Technologies
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_ncd/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <functiondiscoveryapi.h>
#include <functiondiscoveryconstraints.h>
#include <functiondiscoveryprovider.h>
#include <pnpxassoc.h>
#include <wsdxml.h>
#include <wsdxmldom.h>
#include <wsdattachment.h>
#include <wsdbase.h>
#include <wsdclient.h>
#include <wsddisco.h>
#include <wsdhost.h>
#include <wsdtypes.h>
#include <wsdutil.h>

