/*
API: Peer-to-Peer
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_p2p/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <drt.h>
// Deprecated
#include <p2p.h>
//#include <pnrpns.h>
#include <peerdist.h>
#include <pnrpdef.h>

