/*
API: Quality of Service (QOS)
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_qos/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <infocard.h>
// Conflicts with infocard.h
// #include <lpmapi.h>
#include <ntddpsch.h>
#include <qos.h>
#include <qos2.h>
#include <qosobjs.h>
#include <qospol.h>
#include <qossp.h>
#include <traffic.h>
#include <winsock2.h>
