/*
API: Remote Desktop Services
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_termserv/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <audioapotypes.h>
#include <cchannel.h>
#include <pchannel.h>
#include <rdpappcontainerclient.h>
#include <sbtsv.h>
#include <sessdirpublictypes.h>
#include <tsgauthenticationengine.h>
#include <tsgpolicyengine.h>
#include <tspubplugin2com.h>
#include <tspubplugincom.h>
#include <tssbx.h>
#include <tsuserex.h>
#include <tsvirtualchannels.h>
#include <workspaceax.h>
#include <workspaceruntime.h>
#include <workspaceruntimeclientext.h>
#include <wrdsgraphicschannels.h>
#include <wtsapi32.h>
#include <wtsdefs.h>
#include <wtshintapi.h>
#include <wtsprotocol.h>
