/*
API: Routing and Remote Access Service
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_rras/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

#define MPR50 1

// Default Header
#include <windows.h>

// API Headers
#include <ipxrtdef.h>
#include <mgm.h>
#include <mprapi.h>
#include <ras.h>
#include <rasdlg.h>
#include <rasshost.h>
#include <routprot.h>
#include <rtmv2.h>
#include <stm.h>

