/*
API: Security and Identity
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_security/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <aclapi.h>
#include <aclui.h>
#include <adtgen.h>
#include <authz.h>
#include <azroles.h>
#include <bcrypt.h>
#include <casetup.h>
#include <celib.h>
#include <certadm.h>
#include <certbcli.h>
#include <certcli.h>
#include <certenc.h>
#include <certenroll.h>
#include <certexit.h>
#include <certif.h>
#include <certmod.h>
#include <certpol.h>
#include <certpoleng.h>
#include <certsrv.h>
#include <certview.h>
#include <credssp.h>
#include <cryptdlg.h>
#include <cryptuiapi.h>
#include <cryptxml.h>
#include <diagnosticdataquery.h>
#include <diagnosticdataquerytypes.h>
#include <dpapi.h>
#include <dssec.h>
#include <iads.h>
#include <identitycommon.h>
#include <identityprovider.h>
#include <identitystore.h>
#include <keycredmgr.h>
#include <lsalookup.h>
#include <mscat.h>
#include <mssip.h>
#include <ncrypt.h>
#include <ncryptprotect.h>
#include <npapi.h>
//#include <ntlsa.h>
#include <ntsecapi.h>
#include <sas.h>
#include <scesvc.h>
#include <schannel.h>
#include <sddl.h>
#include <securityappcontainer.h>
#include <slpublic.h>
#include <sspi.h>
//#include <subauth.h>
#include <tokenbinding.h>
#include <tpmvscmgr.h>
#include <wincred.h>
#include <wincrypt.h>
#include <winnetwk.h>
#include <winsafer.h>
#include <winscard.h>
#include <winsvc.h>
#include <wintrust.h>
#include <winwlx.h>
#include <xenroll.h>
