/*
API: Structured Storage
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_stg/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <coml2api.h>
#include <propapi.h>
#include <propidlbase.h>
