/*
API: System Services
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_base/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

#undef maxStringLength

// Default Header
#include <windows.h>
// API Headers
#include <windows.system.h>
#include <atlthunk.h>
#include <avrt.h>
#include <imagehlp.h>
#include <dbt.h>
#include <debugapi.h>
#include <enclaveapi.h>
#include <errhandlingapi.h>
#include <fibersapi.h>
#include <handleapi.h>
#include <heapapi.h>
#include <interlockedapi.h>
#include <ioapiset.h>
#include <jobapi.h>
#include <jobapi2.h>
#include <libloaderapi.h>
#include <libloaderapi2.h>
#include <mcx.h>
#include <memoryapi.h>
#include <minidumpapiset.h>
#include <minwinbase.h>
#include <namedpipeapi.h>
#include <namespaceapi.h>
#include <ntenclv.h>
#include <powerbase.h>
#include <powersetting.h>
#include <powrprof.h>
#include <processenv.h>
#include <processthreadsapi.h>
#include <processtopologyapi.h>
#include <profileapi.h>
#include <pwm.h>
#include <realtimeapiset.h>
#include <secext.h>
#include <storprop.h>
#include <synchapi.h>
#include <sysinfoapi.h>
#include <systemtopologyapi.h>
#include <threadpoolapiset.h>
#include <threadpoollegacyapiset.h>
#include <timeprov.h>
#include <timezoneapi.h>
#include <utilapiset.h>
#include <vds.h>
#include <vdslun.h>
#include <versionhelpers.h>
#include <vsadmin.h>
#include <vsmgmt.h>
#include <vsprov.h>
#include <vss.h>
#include <waasapi.h>
#include <waasapitypes.h>
#include <wct.h>
#include <windowsceip.h>
#include <winenclaveapi.h>

// Conflicts with imghelp.h
//#include <dbghelp.h>

// Conflicts with vds.h
// #include <vdshwprv.h>

//#include <winioctl.h>

#ifdef __cplusplus
#include <dispatcherqueue.h>
#include <rtworkq.h>
#include <vswriter.h>
#include <vsbackup.h>
#endif
