/*
API: Tablet PC
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_tablet/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <inked.h>
#include <micaut.h>
#include <msinkaut.h>
#include <msinkaut15.h>
#include <peninputpanel.h>
#include <rectypes.h>
#include <rtscom.h>
#include <tabflicks.h>
#include <tpcshrd.h>

// Redefines Process from comsvcs.h
// #include <recapis.h>

