/*
API: Task Scheduler
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_taskschd/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <mstask.h>
#include <taskschd.h>
