/*
API: Telephony Application Programming
            Interfaces
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_tapi3/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

#ifdef __cplusplus
#include <tapi3.h>
// Conflicts with tapi3?
// #include <TermMgr.h>
// #include <Msputils.h>
// #include <Mspaddr.h>
// #include <Mspbase.h>
// #include <Mspcall.h>
// #include <Msplog.h>
// #include <Mspstrm.h>
// #include <Mspterm.h>
// #include <Mspthrd.h>
// #include <Msptmac.h>
// #include <Msptmvc.h>
// #include <Msptrmvc.h>
// #include <Msptrmac.h>
// #include <Msptrmar.h>
#endif

// API Headers
#include <mdhcp.h>
#include <rend.h>
#include <tapi3ds.h>
#include <tapi3if.h>