/*
API: Text Services Framework
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_tsf/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <ctffunc.h>
#include <ctfspui.h>
#include <ctfutb.h>
#include <inputscope.h>
#include <msaatext.h>
#include <msctf.h>
#include <textstor.h>

#ifdef __cplusplus
#include <msctfmonitorapi.h>
#endif
