/*
API: The Windows Shell
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_shell/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <appmgmt.h>
#include <appnotify.h>
#include <cpl.h>
#include <credentialprovider.h>
#include <dimm.h>
#include <imagetranscode.h>
#include <inputpanelconfiguration.h>
#include <intsafe.h>
#include <intshcut.h>
#include <mobsync.h>
#include <objectarray.h>
#include <pathcch.h>
#include <profinfo.h>
#include <propkeydef.h>
#include <scrnsave.h>
#include <shappmgr.h>
#include <shdeprecated.h>
#include <shidfact.h>

#include <shlwapi.h>
#include <shtypes.h>
#include <storageprovider.h>
#include <syncmgr.h>
#include <thumbcache.h>
#include <thumbnailstreamcache.h>
#include <tlogstg.h>
#include <userenv.h>

#ifdef __cplusplus
using namespace Gdiplus;
#include <shimgdata.h>
#endif

