/*
API: TraceLogging
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_tracelogging/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <traceloggingprovider.h>

#ifdef __cplusplus
#include <traceloggingactivity.h>
#endif
