/*
API: Windows Clustering
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_mscs/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
// Conflicts with pnp (HGROUP)
// #include <cluadmex.h>
// #include <clusapi.h>
// #include <msclus.h>
#include <smbclnt.h>

// #ifdef __cplusplus
// #include <resapi.h>
// #endif
