/*
API: Windows Sockets 2
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_winsock/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>


// API Headers
#include <winsock.h>
#include <ws2atm.h>
#include <ws2spi.h>
#include <ws2tcpip.h>
#include <af_irda.h>
#include <in6addr.h>
#include <mstcpip.h>
#include <mswsock.h>
#include <mswsockdef.h>
#include <nsemail.h>
#include <nspapi.h>
#include <socketapi.h>
#include <sporder.h>
#include <transportsettingcommon.h>
#include <wsipv6ok.h>
#include <wsnwlink.h>
#include <wsrm.h>
