/*
API: Windows Accessibility Features
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_winauto/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <oleacc.h>
#include <uiautomationclient.h>
#include <uiautomationcore.h>

// A billion typedefs because the API header isn't c-friendly
typedef enum ConditionType ConditionType;
typedef enum PropertyConditionFlags PropertyConditionFlags;
typedef enum ProviderType ProviderType;
typedef enum TreeScope TreeScope;
typedef enum AutomationElementMode AutomationElementMode;
typedef enum NavigateDirection NavigateDirection;
typedef enum NormalizeState NormalizeState;
typedef enum AutomationIdentifierType AutomationIdentifierType;
typedef enum EventArgsType EventArgsType;
typedef enum StructureChangeType StructureChangeType;
typedef enum TextEditChangeType TextEditChangeType;
typedef enum AsyncContentLoadedState AsyncContentLoadedState;
typedef enum NotificationKind NotificationKind;
typedef enum NotificationProcessing NotificationProcessing;
typedef enum DockPosition DockPosition;
typedef enum ScrollAmount ScrollAmount;
typedef enum WindowVisualState WindowVisualState;
typedef enum SupportedTextSelection SupportedTextSelection;
typedef enum TextPatternRangeEndpoint TextPatternRangeEndpoint;
typedef enum TextUnit TextUnit;
typedef enum SynchronizedInputType SynchronizedInputType;

typedef struct UiaCondition UiaCondition;
typedef struct UiaCacheRequest UiaCacheRequest;
typedef struct UiaChangeInfo UiaChangeInfo;
typedef struct UiaEventArgs UiaEventArgs;
typedef struct UiaFindParams UiaFindParams;
typedef struct UiaPoint UiaPoint;

#include <uiautomationcoreapi.h>
