/*
API: Windows Multimedia
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_multimedia/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <digitalv.h>
#include <joystickapi.h>
#include <mmeapi.h>
#include <mmiscapi.h>
#include <mmreg.h>
#include <msacm.h>
#include <timeapi.h>
#include <vfw.h>

// Kernel?
//#include <mmddk.h>
