/*
API: Windows Runtime C++ reference
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_winrt/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <accountssettingspaneinterop.h>
#include <activation.h>
#include <activationregistration.h>
#include <asyncinfo.h>
#include <corewindow.h>
#include <dragdropinterop.h>
#include <eventtoken.h>
#include <hstring.h>
#include <inputpaneinterop.h>
#include <inspectable.h>
#include <memorybuffer.h>
#include <playtomanagerinterop.h>
#include <print3dmanagerinterop.h>
#include <printmanagerinterop.h>
#include <radialcontrollerinterop.h>
#include <remotesystemadditionalinfo.h>
#include <restrictederrorinfo.h>
#include <robuffer.h>
#include <rometadata.h>
#include <rometadataapi.h>
#include <rometadataresolution.h>
#include <roparameterizediid.h>
#include <roregistrationapi.h>
#include <shcore.h>
#include <systemmediatransportcontrolsinterop.h>
#include <uiviewsettingsinterop.h>
#include <useractivityinterop.h>
#include <userconsentverifierinterop.h>
#include <weakreference.h>
#include <webauthenticationcoremanagerinterop.h>
#include <windows.data.pdf.interop.h>
#include <windows.devices.display.core.interop.h>
#include <windows.foundation.h>
#include <windows.graphics.capture.interop.h>
#include <windows.graphics.effects.interop.h>
#include <windows.graphics.imaging.interop.h>
#include <windows.media.core.interop.h>
#include <windows.ui.composition.interop.h>
#include <windows.ui.xaml.hosting.referencetracker.h>
#include <windows.ui.xaml.media.dxinterop.h>
#include <windowsstoragecom.h>
#include <winstring.h>
