/*
API: Windows Management Instrumentation
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_wmi/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <wbemdisp.h>
#include <wbemprov.h>


#ifdef __cplusplus
#include <chstring.h>
#include <chptrarr.h>
#include <chstrarr.h>
#include <genlex.h>
#include <objpath.h>
#include <frquery.h>
#include <ThrdBase.h>
#include <wbemtime.h>
#include <refptrco.h>
#include <methodco.h>
#include <instance.h>
#include <StlLock.h>
#include <wbemglue.h>
#define PURE
#endif