/*
API: Windows Biometric Framework
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_secbiomet/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// Don't want ntdef, so...
#define ARGUMENT_PRESENT(ArgumentPointer)    (\
    (CHAR *)((ULONG_PTR)(ArgumentPointer)) != (CHAR *)(NULL) )

// API Headers
#include <winbio.h>
#include <winbio_adapter.h>
