/*
API: Windows Remote Management
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_winrm/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

#define WSMAN_API_VERSION_1_1

// Default Header
#include <windows.h>

// API Headers
#include <wsman.h>
#include <wsmandisp.h>
