/*
API: XAudio2 APIs
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_xaudio2/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers

#undef WINAPI_FAMILY
#include <x3daudio.h>
#define WINAPI_FAMILY WINAPI_FAMILY_DESKTOP_APP
#include <xapo.h>
#include <xapofx.h>
#include <xaudio2.h>
#include <xaudio2fx.h>

#ifdef __cplusplus
#include <xapobase.h>
#include <hrtfapoapi.h>
#endif
