/*
API: XPS Documents
API URL: https://docs.microsoft.com/en-us/windows/win32/api/_xps/
File Creation Time: 2021-06-07

This file was originally generated by winapi_scraper. 
There is no guarantee that this will compile. Some re-ordering may be necessary.
*/

// Default Header
#include <windows.h>

// API Headers
#include <documenttarget.h>
#include <xpsdigitalsignature.h>
#include <xpsobjectmodel.h>
#include <xpsobjectmodel_1.h>
#include <xpsobjectmodel_2.h>
